package com.aelion.todo;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.CrossOrigin;
import org.springframework.web.bind.annotation.DeleteMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.PutMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

import com.aelion.todo.models.Todo;
import com.aelion.todo.models.TodosRepository;


@RequestMapping(path="/api/v1")
@RestController
public class TodoController {
	
	@Autowired 
	// This means to get the bean called heroesRepository
	// Which is auto-generated by Spring, we will use it to handle the data
	private TodosRepository todosRepository;
	
	@CrossOrigin
	@GetMapping("/all")
	public Iterable<Todo> getAll() {
		return this.todosRepository.findAll();
	}
	
	@CrossOrigin
	@PostMapping("/add")
	public Todo add(@RequestBody Todo todo) {
		this.todosRepository.save(todo);
		
		return todo;
	}
	
	@PutMapping("/update")
	public Todo update(@RequestBody Todo todo) {
		this.todosRepository.save(todo);
		return todo;
	}
	
	@DeleteMapping("/delete/{id}")
	public ResponseEntity<?> delete(@PathVariable int id) {
		this.todosRepository.deleteById(id);

		return new ResponseEntity<>(this.getAll(), HttpStatus.OK);
	}
}
